import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useState } from "react";
import { ArrowRight, Eye, EyeOff } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { lovable } from "@/integrations/lovable";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { VnaBrand } from "@/components/vna-brand";
import heroImage from "@/assets/vna-bible-hero.jpg";
import { createHead } from "@/lib/vna-content";

export const Route=createFileRoute("/auth")({head:()=>createHead({title:"Acesso ao VnA Studio",description:"Acesso seguro à central de conteúdo do Vida no Altar."}),component:AuthPage});
function AuthPage(){const navigate=useNavigate();const [mode,setMode]=useState<"signin"|"signup">("signin");const [show,setShow]=useState(false);const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");const data=new FormData(e.currentTarget);const email=String(data.get("email"));const password=String(data.get("password"));const name=String(data.get("name")??"");if(mode==="signup"){const {data:result,error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:window.location.origin+"/auth",data:{display_name:name}}});if(error)setMessage(error.message);else if(!result.session)setMessage("Enviamos um link de confirmação para o seu e-mail.");else navigate({to:"/studio"});}else{const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setMessage("Não foi possível entrar. Confira seu e-mail e senha.");else navigate({to:"/studio"});}setBusy(false)}
async function google(){const result=await lovable.auth.signInWithOAuth("google",{redirect_uri:window.location.origin+"/auth"});if(result.error)setMessage("Não foi possível entrar com o Google.");if(!result.redirected&&!result.error)navigate({to:"/studio"});}
async function forgot(){const email=(document.querySelector('input[name="email"]') as HTMLInputElement|null)?.value;if(!email){setMessage("Digite seu e-mail primeiro.");return;}await supabase.auth.resetPasswordForEmail(email,{redirectTo:window.location.origin+"/reset-password"});setMessage("Se esse e-mail estiver cadastrado, você receberá um link de recuperação.");}
return <main className="grid min-h-screen bg-background lg:grid-cols-[1.05fr_.95fr]"><section className="relative hidden overflow-hidden bg-foreground lg:block"><img src={heroImage} alt="Bíblia aberta sob a luz da manhã" className="h-full w-full object-cover"/><div className="absolute inset-0 bg-foreground/55"/><blockquote className="absolute bottom-14 left-14 max-w-md font-display text-4xl leading-tight text-background">“Marca viva, não improvisada.”</blockquote></section><section className="flex items-center justify-center p-6 sm:p-12"><div className="w-full max-w-md"><VnaBrand/><p className="eyebrow mt-12">VnA Studio</p><h1 className="mt-3 font-display text-4xl">{mode==="signin"?"Entre para continuar":"Crie seu acesso"}</h1><p className="mt-3 text-sm text-muted-foreground">Central interna do Vida no Altar.</p><form onSubmit={submit} className="mt-8 space-y-4">{mode==="signup"&&<Input name="name" required placeholder="Nome completo" className="h-12"/>}<Input name="email" type="email" required placeholder="E-mail" className="h-12"/><div className="relative"><Input name="password" type={show?"text":"password"} required minLength={8} placeholder="Senha" className="h-12 pr-12"/><Button type="button" variant="ghost" size="icon" className="absolute right-1 top-1.5" onClick={()=>setShow(!show)} aria-label="Mostrar senha">{show?<EyeOff/>:<Eye/>}</Button></div>{message&&<p className="border-l-2 border-primary pl-3 text-sm leading-6">{message}</p>}<Button variant="studio" className="h-12 w-full" disabled={busy}>{busy?"Aguarde...":mode==="signin"?"Entrar":"Criar conta"}<ArrowRight/></Button></form><Button variant="outline" className="mt-3 h-12 w-full" onClick={google}>Continuar com Google</Button>{mode==="signin"&&<button className="mt-5 text-sm text-muted-foreground underline" onClick={forgot}>Esqueci minha senha</button>}<p className="mt-8 text-sm text-muted-foreground">{mode==="signin"?"Ainda não tem acesso? ":"Já possui acesso? "}<button className="font-bold text-foreground" onClick={()=>{setMode(mode==="signin"?"signup":"signin");setMessage("")}}>{mode==="signin"?"Criar conta":"Entrar"}</button></p></div></section></main>}