/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CanaisRouteImport } from './routes/canais'
import { Route as ComecarRouteImport } from './routes/comecar'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as AuthenticatedStudioRouteImport } from './routes/_authenticated/studio'
import { Route as AuthenticatedStudioSectionRouteImport } from './routes/_authenticated/studio.$section'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CanaisRoute = CanaisRouteImport.update({
  id: '/canais',
  path: '/canais',
  getParentRoute: () => rootRouteImport,
} as any)
const ComecarRoute = ComecarRouteImport.update({
  id: '/comecar',
  path: '/comecar',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudioRoute = AuthenticatedStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudioSectionRoute =
  AuthenticatedStudioSectionRouteImport.update({
    id: '/$section',
    path: '/$section',
    getParentRoute: () => AuthenticatedStudioRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/canais': typeof CanaisRoute
  '/comecar': typeof ComecarRoute
  '/contato': typeof ContatoRoute
  '/projetos': typeof ProjetosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sobre': typeof SobreRoute
  '/studio': typeof AuthenticatedStudioRouteWithChildren
  '/studio/$section': typeof AuthenticatedStudioSectionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/canais': typeof CanaisRoute
  '/comecar': typeof ComecarRoute
  '/contato': typeof ContatoRoute
  '/projetos': typeof ProjetosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sobre': typeof SobreRoute
  '/studio': typeof AuthenticatedStudioRouteWithChildren
  '/studio/$section': typeof AuthenticatedStudioSectionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/canais': typeof CanaisRoute
  '/comecar': typeof ComecarRoute
  '/contato': typeof ContatoRoute
  '/projetos': typeof ProjetosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sobre': typeof SobreRoute
  '/_authenticated/studio': typeof AuthenticatedStudioRouteWithChildren
  '/_authenticated/studio/$section': typeof AuthenticatedStudioSectionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/canais'
    | '/comecar'
    | '/contato'
    | '/projetos'
    | '/reset-password'
    | '/sobre'
    | '/studio'
    | '/studio/$section'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/canais'
    | '/comecar'
    | '/contato'
    | '/projetos'
    | '/reset-password'
    | '/sobre'
    | '/studio'
    | '/studio/$section'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/canais'
    | '/comecar'
    | '/contato'
    | '/projetos'
    | '/reset-password'
    | '/sobre'
    | '/_authenticated/studio'
    | '/_authenticated/studio/$section'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CanaisRoute: typeof CanaisRoute
  ComecarRoute: typeof ComecarRoute
  ContatoRoute: typeof ContatoRoute
  ProjetosRoute: typeof ProjetosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canais': {
      id: '/canais'
      path: '/canais'
      fullPath: '/canais'
      preLoaderRoute: typeof CanaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comecar': {
      id: '/comecar'
      path: '/comecar'
      fullPath: '/comecar'
      preLoaderRoute: typeof ComecarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/studio': {
      id: '/_authenticated/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AuthenticatedStudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/$section': {
      id: '/_authenticated/studio/$section'
      path: '/$section'
      fullPath: '/studio/$section'
      preLoaderRoute: typeof AuthenticatedStudioSectionRouteImport
      parentRoute: typeof AuthenticatedStudioRoute
    }
  }
}

interface AuthenticatedStudioRouteChildren {
  AuthenticatedStudioSectionRoute: typeof AuthenticatedStudioSectionRoute
}

const AuthenticatedStudioRouteChildren: AuthenticatedStudioRouteChildren = {
  AuthenticatedStudioSectionRoute: AuthenticatedStudioSectionRoute,
}

const AuthenticatedStudioRouteWithChildren =
  AuthenticatedStudioRoute._addFileChildren(AuthenticatedStudioRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedStudioRoute: typeof AuthenticatedStudioRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedStudioRoute: AuthenticatedStudioRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CanaisRoute: CanaisRoute,
  ComecarRoute: ComecarRoute,
  ContatoRoute: ContatoRoute,
  ProjetosRoute: ProjetosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
